
package com.bakki.test.tshirt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-12-25T21:03:31.099-05:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "TshirtFault", targetNamespace = "http://mulesoft.org/tshirt-service")
public class TshirtFault_Exception extends Exception {
    
    private com.bakki.test.tshirt.TshirtFault tshirtFault;

    public TshirtFault_Exception() {
        super();
    }
    
    public TshirtFault_Exception(String message) {
        super(message);
    }
    
    public TshirtFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TshirtFault_Exception(String message, com.bakki.test.tshirt.TshirtFault tshirtFault) {
        super(message);
        this.tshirtFault = tshirtFault;
    }

    public TshirtFault_Exception(String message, com.bakki.test.tshirt.TshirtFault tshirtFault, Throwable cause) {
        super(message, cause);
        this.tshirtFault = tshirtFault;
    }

    public com.bakki.test.tshirt.TshirtFault getFaultInfo() {
        return this.tshirtFault;
    }
}
