package com.bakki.test.tshirt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-12-25T21:03:31.254-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://mulesoft.org/tshirt-service", name = "TshirtServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface TshirtServicePortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "OrderTshirtResponse", targetNamespace = "http://mulesoft.org/tshirt-service", partName = "body")
    @WebMethod(operationName = "OrderTshirt", action = "http://mulesoft.org/tshirt-service/order-tshirt")
    public OrderTshirtResponse orderTshirt(
        @WebParam(partName = "body", name = "OrderTshirt", targetNamespace = "http://mulesoft.org/tshirt-service")
        OrderTshirt body
    ) throws TshirtFault_Exception;

    @WebResult(name = "inventory", targetNamespace = "")
    @RequestWrapper(localName = "ListInventory", targetNamespace = "http://mulesoft.org/tshirt-service", className = "com.bakki.test.tshirt.ListInventory")
    @WebMethod(operationName = "ListInventory", action = "http://mulesoft.org/tshirt-service/list-inventory")
    @ResponseWrapper(localName = "ListInventoryResponse", targetNamespace = "http://mulesoft.org/tshirt-service", className = "com.bakki.test.tshirt.ListInventoryResponse")
    public java.util.List<com.bakki.test.tshirt.InventoryItem> listInventory() throws TshirtFault_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TrackOrderResponse", targetNamespace = "http://mulesoft.org/tshirt-service", partName = "body")
    @WebMethod(operationName = "TrackOrder", action = "http://mulesoft.org/tshirt-service/track-order")
    public TrackOrderResponse trackOrder(
        @WebParam(partName = "body", name = "TrackOrder", targetNamespace = "http://mulesoft.org/tshirt-service")
        TrackOrder body
    ) throws TshirtFault_Exception;
}
