package com.bakka.testing.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-12-28T20:04:31.453-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ws.cdyne.com/", name = "IP2GeoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IP2GeoSoap {

    /**
     * Use a License Key of 0 for Testing
     */
    @WebResult(name = "ResolveIPResult", targetNamespace = "http://ws.cdyne.com/")
    @RequestWrapper(localName = "ResolveIP", targetNamespace = "http://ws.cdyne.com/", className = "com.bakka.testing.clients.ResolveIP")
    @WebMethod(operationName = "ResolveIP", action = "http://ws.cdyne.com/ResolveIP")
    @ResponseWrapper(localName = "ResolveIPResponse", targetNamespace = "http://ws.cdyne.com/", className = "com.bakka.testing.clients.ResolveIPResponse")
    public com.bakka.testing.clients.IPInformation resolveIP(
        @WebParam(name = "ipAddress", targetNamespace = "http://ws.cdyne.com/")
        java.lang.String ipAddress,
        @WebParam(name = "licenseKey", targetNamespace = "http://ws.cdyne.com/")
        java.lang.String licenseKey
    );
}
